# Generated by Django 4.2.4 on 2023-08-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
